apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: simcax-dk
  namespace: argocd-skov-run
  annotations:
    argocd-image-updater.argoproj.io/image-list: simcax-dk=simcax/simcax.dk:0.0.x
    argocd-image-updater.argoproj.io/write-back-method: git:repocreds
    argocd-image-updater.argoproj.io/git-branch: master
    argocd-image-updater.argoproj.io/simcax.dk.pull-secret: pullsecret:cd-skov-run/regcred
spec:
  project: default

  source: 
    repoURL: https://github.com/simcax/deploy-simcax.dk.git
    targetRevision: HEAD
    path: simcax-dk
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: simcax-dk
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
